using UnityEngine;

public static class RandomNameGenerator
{
    public static string[] nicknames =
    {
        "wanyama",
        "SoulRocker",
        "World Pas Ouf",
        "N0vie",
        "Sejo I",
        "Hitoshiro",
        "KEVINSNIPER",
        "chevaro",
        "xo warren94",
        "StonedWizardeu",
        "x3legend13",
        "Sergiollv",
        "Sayli",
        "Alpq17 v2",
        "BUCETERO",
        "Aryast",
        "BOPPY BOBBY",
        "No Brain P1",
        "POV007",
        "Xzalem",
        "tfw is my",
        "Lésitaril",
        "Hurrij2",
        "TropZs",
        "Rito Solal",
        "Meralfo",
        "Mariolvarez",
        "bullets88",
        "elmoroco",
        "Logullo8",
        "DerDieselBomber",
        "TheCreeLy",
        "prono1337",
        "argo03",
        "Grill17",
        "Ginger4u",
        "JapanTsuki",
        "N0T Y0UR TIME",
        "GrinningDem0n",
        "Gaenyrim",
        "Manquiito",
        "VaroDrum",
        "K3vxn",
        "WinEpic",
        "MrRevillo0815",
        "Holymakkaroni",
        "juanm10",
        "DragonB3ar",
        "KWJ GankedByTai",
        "Qlowntje",
        "CaDa1",
        "Szabolcs99",
        "SeiyoNashiOGC",
        "ZgD Jibeyyy",
        "Xpower974",
        "Toilet Clown",
        "Guadamajud",
        "ReD Knight SQZ",
        "kikki92",
        "hallmaster",
        "daveypanda",
        "Bmoral",
        "Joe Harper",
        "lll NesQuick",
        "Mikachikito",
        "DerAllmächtige44",
        "ZyzzTheKing",
        "Zyppi31",
        "Olliewollie",
        "Ned Bigby",
        "himiky",
        "PowerxDDD",
        "Heort",
        "Dr Nonimontes",
        "Javielos",
        "YabguHan",
        "BastaKilla",
        "SickJacken96",
        "Motelles",
        "Ikhyun Kim",
        "Strong Somang",
        "DeadGemini",
        "ShorterACE",
        "Quacken Slayer",
        "200IQPLAYS",
        "sticklermeeseek",
        "basalist",
        "boom blast",
        "Lyks",
        "95270217del",
        "quiet practice",
        "yourdogass",
        "punkstar",
        "apotheosís",
        "Haka",
        "Wind19",
        "Luha",
        "Sanha",
        "Meguitan",
        "Lightcax",
        "Foxy",
        "Miyamoto Musashi",
        "Lyrics Suçks",
        "Sung Suhø",
        "sad suffering",
        "Kiwi",
        "BaIIack",
        "stepz01",
        "Blacknoize",
        "RoughBeanz",
        "Dìesel",
        "eXyu",
        "The Humbler",
        "Heartbroken",
        "young7",
        "xuee",
        "we arent serious",
        "IN0RI",
        "Yozu",
        "Largente",
        "Shogo2",
        "Aaron Song",
        "MGUTIS1",
        "AhernxPt",
        "Batikaa",
        "Guifei",
    };

    public static string GenerateRandomName()
    {
        int randomIndexForNickNames = Random.Range(0, nicknames.Length);
        return nicknames[randomIndexForNickNames];
    }
}